import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Page1 from "@/app/Page1/Page"
import Page2 from "@/app/Page2/Page"
import Page3 from "@/app/Page3/Page"
import Navbar from "@/components/Navbar/Navbar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className=""
      >
        <Navbar />
        {children}
        <Page1 />
        <Page2 />
        <Page3 />
      </body>
    </html>
  );
}
